name: voxtourai_gps_spoofer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+106

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.1.0
  http: ^1.2.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  package_info_plus: ^9.0.0
  flutter_background: ^1.2.0
  flutter_local_notifications: ^17.2.1
  flutter_bloc: ^9.1.1
  copy_with_extension: ^12.1.0
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  copy_with_extension_gen: ^12.1.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
